name: Oracle Cloud - Create Instance

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *' # Runs automatically every 15 minutes

jobs:
  run-builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install OCI CLI
        run: |
          curl -L -O https://githubusercontent.com
          chmod +x install.sh
          ./install.sh --accept-all-defaults
          echo "/home/runner/bin" >> $GITHUB_PATH

      - name: Configure OCI Auth
        run: |
          mkdir -p ~/.oci
          echo "${{ secrets.OCI_CONFIG }}" > ~/.oci/config
          echo "${{ secrets.OCI_KEY_FILE }}" > ~/.oci/oracle.pem
          chmod 600 ~/.oci/config ~/.oci/oracle.pem

      - name: Attempt to Launch 24GB Server
        run: |
          export PATH=$PATH:/home/runner/bin
          oci compute instance launch \
            --availability-domain "InXg:AP-MUMBAI-1-AD-1" \
            --compartment-id ${{ vars.OCI_COMPARTMENT_ID }} \
            --shape ${{ vars.OCI_INSTANCE_SHAPE }} \
            --shape-config "{\"ocpus\": ${{ vars.OCI_OCPUS }}, \"memoryInGBs\": ${{ vars.OCI_MEMORY_IN_GBS }}}" \
            --subnet-id ${{ secrets.OCI_SUBNET_ID }} \
            --display-name "Minecraft-Multiverse-Server" \
            --image-id "ocid1.image.oc1.ap-mumbai-1.aaaaaaaaj7yvxun7b3vuyasw2w7y46shg6p24c2cljfe67n544oxunsm7hka" \
            --metadata "{\"ssh_authorized_keys\": \"${{ vars.OCI_SSH_PUBLIC_KEY }}\"}"
